PDS(Python for DS)
Practical 4

Name : Raj Upadhyay                  Roll no. : S045
Class : SYIT                         Batch : 1st
Date of Assignment : 05/08/2026      Date of Submission : 05/08/2026

a. Write a python code to create Numpy Array.

In [8]:
import numpy as np
a = np.array([1,2,3])

print(a)
print("Raj_45")

[1 2 3]
Raj_45


b. Write a python code to demonstrate basic operations on single array.

In [11]:
import numpy as np
a = np.array([1,2,3,4,5])

print(a+2)
print("Raj_45")

[3 4 5 6 7]
Raj_45


c. Write a python code to create array with 10 elements and slice element
from 1st to 5th element.

In [16]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])

print(a[0:5])
print(a[5:9])
print("Raj_45")

[1 2 3 4 5]
[6 7 8 9]
Raj_45


d. Write a python code to sort an array alphabetically.

In [17]:
import numpy as np
a=np.array(["Raj","Amit","Kaushal","Jay"])

print(np.sort(a))
print("Raj_45")

['Amit' 'Jay' 'Kaushal' 'Raj']
Raj_45


e. Write a python code to create a filter array that will return maximum
values from an array.

In [18]:
import numpy as np
a=np.array([10,25,30,45,50,20])

print(a[a>40])
print("Raj_45")

[45 50]
Raj_45
